@extends('layouts.app')
@section('title','AI Content Generator')
@section('content')
<div class="page-heading"><div><p class="eyebrow">A GOOD BRIEF. A GREAT BEGINNING.</p><h1>AI Content Generator<span class="title-dot">.</span></h1><p class="muted mt-2">Tell us what you have in mind. Shape the ideas that come next.</p></div></div>
<div class="grid xl:grid-cols-[minmax(0,1fr)_300px] gap-6 items-start">
<form action="{{ route('campaigns.store') }}" method="post" class="panel" id="campaign-form">@csrf
<div class="section-heading border-b border-zinc-100"><div><h2>Your campaign brief</h2><p class="muted text-sm mt-1">All fields are required unless marked optional.</p></div><span class="step-label">01 / BRIEF</span></div>
<div class="form-body space-y-6">
<div class="grid md:grid-cols-2 gap-5"><label>Campaign goal<input name="campaign_goal" value="{{ old('campaign_goal') }}" placeholder="e.g. Increase weekend pizza orders" required maxlength="255"></label><label>Target audience<input name="target_audience" value="{{ old('target_audience') }}" placeholder="e.g. University students and young adults" required maxlength="255"></label></div>
<label>Product / promotion<input name="product_promotion" value="{{ old('product_promotion') }}" placeholder="e.g. Pizza Combo — include only confirmed offer details" required maxlength="255"><span class="field-hint">Include any confirmed prices or terms. AI should never invent an offer.</span></label>
<fieldset><legend class="mb-2 font-medium text-sm">Where will you share it?</legend><div class="grid sm:grid-cols-3 gap-3">@foreach(\App\Models\Post::PLATFORMS as $platform)<label class="platform-choice"><input type="checkbox" name="platforms[]" value="{{ $platform }}" @checked(in_array($platform, old('platforms',['Instagram'])))><x-platform :platform="$platform"/></label>@endforeach</div><p class="field-hint">Choose one or more platforms. One post per day, per platform.</p></fieldset>
<div class="grid md:grid-cols-2 gap-5"><label>Campaign duration<select id="duration"><option value="3">3 days</option><option value="7" selected>7 days</option><option value="14">14 days</option><option value="custom">Custom date range</option></select></label><label>Tone<select name="tone">@foreach(['Casual','Fun','Professional','Promotional'] as $tone)<option @selected(old('tone','Fun') === $tone)>{{ $tone }}</option>@endforeach</select></label></div>
<div class="grid md:grid-cols-2 gap-5"><label>Start date<input type="date" id="start-date" name="start_date" value="{{ old('start_date',today()->toDateString()) }}" min="{{ today()->toDateString() }}" required></label><label>End date<input type="date" id="end-date" name="end_date" value="{{ old('end_date',today()->addDays(6)->toDateString()) }}" min="{{ today()->toDateString() }}" required><span class="field-hint">Up to 14 days per campaign.</span></label></div>
<label>Additional instructions <span class="muted font-normal">(optional)</span><textarea name="additional_instructions" rows="4" maxlength="2000" placeholder="e.g. Focus on sharing meals with friends and keep captions short.">{{ old('additional_instructions') }}</textarea></label>
<div class="notice notice-neutral mb-0"><x-icon name="info"/><span>Generated ideas are saved as drafts. You decide what gets approved and scheduled.</span></div>
</div><div class="form-footer"><button name="mode" value="gemini" class="btn btn-primary" data-generate><x-icon name="spark"/>Generate Content Plan</button><button name="mode" value="sample" class="btn btn-secondary" data-generate>Try Sample Plan</button><p id="generation-status" class="field-hint w-full" role="status">Sample plans use preset fictional copy; no AI request is made.</p></div>
</form>
<aside class="space-y-5"><div class="panel p-6"><div class="accent-icon"><x-icon name="spark"/></div><h2 class="mt-4">Your brief, made better.</h2><p class="muted text-sm mt-3 leading-relaxed">Specific goals and clear details give AI a stronger starting point.</p><ol class="brief-tips"><li><strong>Start with the outcome</strong><p>More weekend orders? More conversation? Pick one clear goal.</p></li><li><strong>Keep the facts grounded</strong><p>Only include offers and details your team has confirmed.</p></li><li><strong>Make it sound like you</strong><p>Choose a tone and add any brand language to keep in mind.</p></li></ol></div><div class="panel p-6"><p class="eyebrow">THE NEXT STEPS</p><div class="workflow-list"><span>01 <strong>Generate a draft</strong></span><span>02 <strong>Review & refine</strong></span><span>03 <strong>Approve & schedule</strong></span><span>04 <strong>Hand off to your platform</strong></span></div></div></aside>
</div>
@endsection
