@extends('layouts.app')
@section('title','Content Calendar')
@section('content')
<div class="page-heading"><div><p class="eyebrow">SEE THE BIGGER PICTURE</p><h1>Content Calendar<span class="title-dot">.</span></h1><p class="muted mt-2">Give every idea its moment.</p></div><a class="btn btn-primary" href="{{ route('campaigns.create') }}"><x-icon name="plus"/>Generate New Content</a></div>
<section class="panel overflow-hidden"><div class="section-heading flex-wrap gap-4"><div class="flex items-center gap-3"><h2 class="calendar-month">{{ $month->format('F Y') }}</h2><a class="icon-button" href="{{ route('calendar',['month'=>$month->subMonth()->format('Y-m')]) }}" aria-label="Previous month"><x-icon name="chevron" class="rotate-180"/></a><a class="icon-button" href="{{ route('calendar',['month'=>$month->addMonth()->format('Y-m')]) }}" aria-label="Next month"><x-icon name="chevron"/></a><a class="btn btn-secondary" href="{{ route('calendar') }}">Today</a></div><div class="flex gap-2">@foreach(\App\Models\Post::STATUSES as $status)<x-status :status="$status"/>@endforeach</div></div>
<div class="hidden md:block"><div class="calendar-weekdays">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day)<span>{{ $day }}</span>@endforeach</div><div class="calendar-grid">@for($day=$start; $day<=$end; $day=$day->addDay())<div @class(['calendar-day','other-month'=>$day->month!==$month->month])><span @class(['day-number','is-today'=>$day->isToday()])>{{ $day->day }}</span>@foreach($posts->get($day->toDateString(),collect()) as $post)<a href="{{ route('posts.show',$post) }}" class="calendar-event event-{{ strtolower($post->status) }}"><span class="flex gap-1 items-center"><x-icon :name="$post->platform"/><span>{{ substr($post->scheduled_time ?? $post->suggested_time,0,5) }}</span></span><strong>{{ $post->post_idea }}</strong><small>{{ $post->status }}{{ $post->campaign->is_demo ? ' · Sample' : '' }}</small></a>@endforeach</div>@endfor</div></div>
<div class="md:hidden p-4"><p class="eyebrow mb-4">MONTHLY AGENDA · MYT</p>@php($hasAgenda=false)@for($day=$month->startOfMonth(); $day<=$month->endOfMonth(); $day=$day->addDay())@if($posts->has($day->toDateString()))@php($hasAgenda=true)<section class="agenda-day"><h3>{{ $day->format('l, j F') }}</h3>@foreach($posts->get($day->toDateString()) as $post)<a class="agenda-post" href="{{ route('posts.show',$post) }}"><div class="flex justify-between gap-2"><x-platform :platform="$post->platform"/><x-status :status="$post->status"/></div><strong>{{ $post->post_idea }}</strong><small>{{ substr($post->scheduled_time ?? $post->suggested_time,0,5) }} MYT {{ $post->campaign->is_demo ? ' · Sample' : '' }}</small></a>@endforeach</section>@endif
@endfor @if(!$hasAgenda)<div class="empty-state"><x-icon name="calendar"/><h3>A little room for fresh ideas</h3><p>No posts planned this month.</p><a class="text-link" href="{{ route('campaigns.create') }}">Generate Content<x-icon name="arrow"/></a></div>@endif</div>
</section><p class="field-hint mt-4">Drafts and approved posts appear on their planned date. Scheduled posts appear on their confirmed date. All times are MYT.</p>
@endsection

