@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<div class="page-heading"><div><p class="eyebrow">YOUR CONTENT, IN FOCUS</p><h1>Dashboard<span class="title-dot">.</span></h1><p class="muted mt-2">A good day to make something worth sharing.</p></div><a href="{{ route('campaigns.create') }}" class="btn btn-primary"><x-icon name="plus"/>Generate New Content</a></div>
@if($due->isNotEmpty())<div class="notice notice-review mb-6"><x-icon name="clock"/><div><strong>{{ $due->count() }} {{ Str::plural('post', $due->count()) }} due for manual posting</strong><p class="mt-1 text-sm">Their scheduled time has passed. Copy the caption and post manually, then mark as Posted.</p><div class="flex flex-wrap gap-2 mt-3">@foreach($due->take(3) as $p)<a href="{{ route('posts.show',$p) }}" class="btn btn-secondary text-xs py-1.5"><x-platform :platform="$p->platform" :label="false"/>{{ Str::limit($p->post_idea,30) }}</a>@endforeach@if($due->count() > 3)<a href="{{ route('scheduled.index') }}" class="btn btn-secondary text-xs py-1.5">+{{ $due->count()-3 }} more</a>@endif</div></div></div>@endif
<div class="stats-grid">
    @foreach([['Total Posts',$total,'file',null,'All your content in one place'],['Draft Posts',$counts['Draft'] ?? 0,'file','Draft','Ready for your review'],['Approved Posts',$counts['Approved'] ?? 0,'check','Approved','Ready to find their time'],['Scheduled Posts',$counts['Scheduled'] ?? 0,'calendar','Scheduled','Planned and on the calendar'],['Posted',$counts['Posted'] ?? 0,'check','Posted','Published successfully']] as [$label,$number,$icon,$filter,$hint])
    <a href="{{ route('posts.index', $filter ? ['status'=>$filter] : []) }}" class="stat-card"><div class="flex justify-between items-center"><span>{{ $label }}</span><x-icon :name="$icon"/></div><strong class="stat-number">{{ str_pad($number, 2, '0', STR_PAD_LEFT) }}</strong><small>{{ $hint }}</small></a>
    @endforeach
</div>
<div class="grid xl:grid-cols-[minmax(0,1fr)_300px] gap-6 mt-7">
    <section class="panel min-w-0"><div class="section-heading"><div><h2>Upcoming posts</h2><p class="muted text-sm mt-1">The next five posts on your calendar.</p></div><a class="text-link" href="{{ route('scheduled.index') }}">View all <x-icon name="arrow"/></a></div>
    <div class="table-wrap"><table><thead><tr><th>Content</th><th>Scheduled for</th><th>Status</th><th><span class="sr-only">Review post</span></th></tr></thead><tbody>
    @forelse($upcoming as $post)
    <tr><td><div class="flex gap-3 items-center"><x-platform :platform="$post->platform" :label="false"/><div><a class="row-title" href="{{ route('posts.show',$post) }}">{{ $post->post_idea }}</a><small>{{ $post->platform }} · {{ $post->content_type }} @if($post->campaign->is_demo) · Sample @endif</small></div></div></td><td class="whitespace-nowrap">{{ $post->scheduled_date->format('d M Y') }}<small>{{ $post->scheduledAt()->format('g:i A') }} MYT</small></td><td><x-status :status="$post->status"/></td><td><a href="{{ route('posts.show',$post) }}" class="icon-button" aria-label="View {{ $post->post_idea }}"><x-icon name="chevron"/></a></td></tr>
    @empty<tr><td colspan="4"><div class="empty-state"><x-icon name="calendar"/><h3>Your next post starts here</h3><p>Review and approve a draft, then choose its posting time.</p><a class="text-link" href="{{ route('posts.index') }}">Review content <x-icon name="arrow"/></a></div></td></tr>@endforelse
    </tbody></table></div></section>
    <section class="panel quick-actions"><p class="eyebrow">KEEP THINGS MOVING</p><h2>Quick actions</h2><a href="{{ route('campaigns.create') }}" class="quick-link"><span class="quick-icon"><x-icon name="spark"/></span><span>Generate new content<small>Turn a brief into a plan</small></span><x-icon name="chevron"/></a><a href="{{ route('calendar') }}" class="quick-link"><span class="quick-icon"><x-icon name="calendar"/></span><span>View content calendar<small>See the bigger picture</small></span><x-icon name="chevron"/></a><a href="{{ route('scheduled.index') }}" class="quick-link"><span class="quick-icon"><x-icon name="clock"/></span><span>View scheduled posts<small>Get ready for what’s next</small></span><x-icon name="chevron"/></a><div class="text-sm muted border-t border-zinc-200 pt-4 mt-3">Scheduling is internal. Posts are handed off manually to each platform.</div></section>
</div>
<section class="mt-8"><div class="section-heading px-0"><div><h2>Recent AI generated content</h2><p class="muted text-sm mt-1">A fresh perspective. Always yours to review.</p></div><a href="{{ route('posts.index') }}" class="text-link">Content library <x-icon name="arrow"/></a></div><div class="grid sm:grid-cols-2 2xl:grid-cols-4 gap-4">@forelse($recent as $post)@include('posts.card')@empty<div class="panel empty-state sm:col-span-2"><p>No content yet. Start with your first campaign.</p><a class="btn btn-primary" href="{{ route('campaigns.create') }}">Generate Content</a></div>@endforelse</div></section>
@endsection
