@extends('layouts.app')
@section('title','Review Content')
@section('content')
<a href="{{ route('posts.index') }}" class="text-link mb-5 inline-flex"><x-icon name="arrow" class="rotate-180"/>Back to content library</a>
<div class="page-heading"><div><p class="eyebrow">MAKE IT YOUR OWN</p><h1>Review Content<span class="title-dot">.</span></h1><p class="muted mt-2">{{ $post->campaign->campaign_goal }} @if($post->campaign->is_demo)<span class="sample-label">SAMPLE CAMPAIGN</span>@endif</p></div><x-status :status="$post->status"/></div>
@if(session('handoff'))<div class="notice notice-neutral" role="status"><x-icon name="info"/><div><strong>{{ session('handoff.message') }}</strong><p class="mt-1">Copy your approved caption and continue manually. Nothing has been published.</p><a class="btn btn-secondary mt-3" href="{{ session('handoff.url') }}" target="_blank" rel="noopener noreferrer">Open {{ session('handoff.platform') }}<x-icon name="arrow"/></a></div></div>@endif
@if($post->status === 'Draft')<div class="notice notice-review"><x-icon name="spark"/><span><strong>AI Generated Recommendation — Review Required</strong><br>Check all claims, promotion details and brand voice before approving.</span></div>@endif
@if($post->status === 'Posted')<div class="notice notice-success" role="status"><x-icon name="check"/><span><strong>Marked as Posted</strong> — This post has been confirmed as published manually on {{ $post->platform }}.</span></div>@endif
<div class="grid xl:grid-cols-[minmax(0,1fr)_380px] gap-6 items-start">
<div class="space-y-6">
<form method="post" action="{{ route('posts.update',$post) }}" class="panel" id="post-editor">@csrf @method('PUT')<input type="hidden" name="version" value="{{ $post->version }}">
<div class="section-heading border-b border-zinc-100"><h2>Post details</h2><span class="text-sm muted">{{ $post->content_type }}</span></div>
<fieldset class="form-body space-y-5" @disabled(in_array($post->status, ['Scheduled','Posted']))>
<div class="grid md:grid-cols-2 gap-5"><label>Platform<select name="platform" data-preview="platform">@foreach(\App\Models\Post::PLATFORMS as $platform)<option @selected(old('platform',$post->platform) === $platform)>{{ $platform }}</option>@endforeach</select></label><label>Content type<input value="{{ $post->content_type }}" readonly class="read-only"></label></div>
<label>Post idea / content concept<input name="post_idea" value="{{ old('post_idea',$post->post_idea) }}" required maxlength="255" data-preview="idea"></label>
<label>Hook <span class="muted font-normal">(optional)</span><input name="hook" value="{{ old('hook',$post->hook) }}" maxlength="500" data-preview="hook"><span class="field-hint">A short opening line, especially useful for TikTok.</span></label>
<label>Caption<textarea name="caption" rows="6" maxlength="2200" required data-preview="caption">{{ old('caption',$post->caption) }}</textarea><span class="field-hint"><span id="caption-count">{{ mb_strlen(old('caption',$post->caption)) }}</span> / 2,200 characters</span></label>
<label>Call to action<input name="call_to_action" value="{{ old('call_to_action',$post->call_to_action) }}" required maxlength="255" data-preview="cta"></label>
<label>Hashtags<input name="hashtags" value="{{ is_array(old('hashtags')) ? implode(' ',old('hashtags')) : old('hashtags',implode(' ',$post->hashtags)) }}" data-preview="hashtags"><span class="field-hint">Up to 5 hashtags, separated by spaces.</span></label>
<div class="grid md:grid-cols-2 gap-5"><label>Planned date<input type="date" name="planned_date" value="{{ old('planned_date',$post->planned_date->toDateString()) }}" required data-preview="date"></label><label>Suggested time (MYT)<input type="time" name="suggested_time" value="{{ old('suggested_time',substr($post->suggested_time,0,5)) }}" required data-preview="time"></label></div>
<div class="rationale"><x-icon name="spark"/><div><strong>{{ $post->campaign->is_demo ? 'Sample planning rationale' : 'AI planning rationale' }}</strong><p>{{ $post->ai_reason }}</p></div></div>
</fieldset>
@if(!in_array($post->status, ['Scheduled','Posted']))<div class="form-footer"><button class="btn btn-primary"><x-icon name="check"/>Save Changes</button><span class="field-hint">Edits return this post to Draft for a fresh review.</span></div>@else<div class="form-footer"><p class="muted text-sm">{{ $post->status === 'Scheduled' ? 'Cancel the schedule before editing the content.' : 'This post has been marked as posted and is read-only.' }}</p></div>@endif
</form>
@if($post->status === 'Draft')
<section class="panel p-6"><h2>Ready to approve?</h2><p class="muted text-sm mt-2 mb-5">Approve the saved version after reviewing the copy and preview.</p><div class="flex flex-wrap gap-3"><form action="{{ route('posts.approve',$post) }}" method="post" data-requires-saved>@csrf<input type="hidden" name="version" value="{{ $post->version }}"><button class="btn btn-primary"><x-icon name="check"/>Approve Post</button></form><form method="post" action="{{ route('posts.destroy',$post) }}" data-confirm="Delete this draft? This cannot be undone.">@csrf @method('DELETE')<input type="hidden" name="version" value="{{ $post->version }}"><button class="btn btn-danger">Delete Draft</button></form></div><p id="unsaved-warn" class="text-sm text-red-700 mt-3 hidden" role="status">Save your changes before approving or scheduling.</p></section>
@elseif($post->status === 'Posted')
<section class="panel p-6"><h2>Post confirmed as published</h2><p class="muted text-sm mt-2">This post has been manually marked as posted. No further actions are required.</p></section>
@else
<section class="panel" id="schedule"><div class="section-heading border-b border-zinc-100"><h2>{{ $post->status === 'Scheduled' ? 'Edit schedule' : 'Schedule this post' }}</h2><x-icon name="calendar"/></div><form method="post" action="{{ route('posts.schedule',$post) }}" class="form-body space-y-5" data-requires-saved>@csrf<input type="hidden" name="version" value="{{ $post->version }}"><div class="grid sm:grid-cols-2 gap-5"><label>Posting date<input type="date" name="scheduled_date" required min="{{ today()->toDateString() }}" value="{{ old('scheduled_date',($post->scheduled_date ?? $post->planned_date)->toDateString()) }}" data-preview="date"></label><label>Posting time (MYT)<input type="time" name="scheduled_time" required value="{{ old('scheduled_time',substr($post->scheduled_time ?? $post->suggested_time,0,5)) }}" data-preview="time"></label></div><p class="field-hint">Malaysia time (UTC+8). Scheduling saves the plan internally; it does not publish to social media.</p><button class="btn btn-primary"><x-icon name="calendar"/>{{ $post->status === 'Scheduled' ? 'Save Schedule' : 'Schedule Post' }}</button><p id="unsaved-warn-schedule" class="text-sm text-red-700 hidden" role="status">Save your content changes and approve them before scheduling.</p></form>@if($post->status === 'Scheduled')<form class="form-footer" method="post" action="{{ route('posts.cancelSchedule',$post) }}" data-confirm="Cancel this schedule? Your approved content will be kept.">@csrf @method('DELETE')<input type="hidden" name="version" value="{{ $post->version }}"><button class="btn btn-secondary">Cancel Schedule</button></form>@endif</section>
<section class="panel p-6"><h2>Continue to your platform</h2><p class="muted text-sm mt-2 mb-5">Connections are a future integration. Copy the caption to post manually.</p><div class="flex flex-wrap gap-3">@foreach(\App\Models\Post::PLATFORMS as $platform)<form action="{{ route('posts.platform',$post) }}" method="post" data-requires-saved>@csrf<input type="hidden" name="platform" value="{{ $platform }}"><button class="btn btn-secondary"><x-icon :name="$platform"/>Post to {{ $platform }}</button></form>@endforeach</div>@if($post->status === 'Scheduled')<div class="mt-4 pt-4 border-t border-zinc-100"><form action="{{ route('posts.markPosted',$post) }}" method="post" data-confirm="Mark this post as published? This confirms you have manually posted it on your platform.">@csrf<input type="hidden" name="version" value="{{ $post->version }}"><button class="btn btn-secondary text-emerald-700 border-emerald-200 hover:bg-emerald-50"><x-icon name="check"/>Mark as Posted</button></form><p class="field-hint mt-2">Confirm that you have published this post manually on the platform.</p></div>@endif</section>
@endif
</div>
<aside class="xl:sticky xl:top-6 space-y-4"><div class="flex justify-between items-center"><h2>Post preview</h2><span class="preview-live">LIVE PREVIEW</span></div><p class="field-hint">An illustration of your post, not an exact platform preview.</p><article class="post-preview"><div class="preview-header"><span class="preview-avatar">US</span><div><strong>US Pizza</strong><small id="preview-platform">{{ $post->platform }}</small></div><span class="ml-auto text-zinc-400" aria-hidden="true">•••</span></div><div class="media-placeholder"><x-icon name="image"/><strong>Room for your creative</strong><span>No media attached</span></div><div class="preview-copy"><p id="preview-hook" class="font-semibold mb-2">{{ $post->hook }}</p><p id="preview-caption" class="whitespace-pre-wrap">{{ $post->caption }}</p><p id="preview-cta" class="font-semibold mt-4">{{ $post->call_to_action }}</p><p id="preview-hashtags" class="text-red-700 mt-3">{{ implode(' ',$post->hashtags) }}</p></div><div class="preview-date"><x-icon name="calendar"/><span><span id="preview-date">{{ ($post->scheduled_date ?? $post->planned_date)->toDateString() }}</span> · <span id="preview-time">{{ substr($post->scheduled_time ?? $post->suggested_time,0,5) }}</span> MYT<br><small>{{ $post->status === 'Scheduled' ? 'Scheduled internally' : ($post->status === 'Posted' ? 'Marked as posted' : 'Proposed time · not scheduled') }}</small></span></div></article><div class="flex flex-wrap gap-2"><button class="btn btn-secondary flex-1" data-copy="caption"><x-icon name="copy"/>Copy Caption</button><button class="btn btn-secondary" data-copy="hashtags">Copy Hashtags</button></div><p class="field-hint">Copy Caption includes the hook and call to action. Copy hashtags separately.</p></aside>
</div>
@endsection
